import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(p => p.id === id) || { imageUrl: '', imageHint: '' };

export const products: Product[] = [
  {
    id: '1',
    name: 'Aura Timepiece',
    description: 'Elegant watch with a minimalist design.',
    longDescription: 'The Aura Timepiece is a masterclass in minimalist design and precision engineering. Featuring a sapphire crystal face, a stainless steel case, and a genuine leather strap, it is both durable and stylish. Water-resistant up to 50 meters, it is the perfect companion for every occasion.',
    price: 249.99,
    category: 'Accessories',
    rating: 4.8,
    reviews: 120,
    stock: 15,
    imageUrl: findImage('product-1').imageUrl,
    imageHint: findImage('product-1').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod1-1/600/800', hint: 'watch face' },
      { url: 'https://picsum.photos/seed/prod1-2/600/800', hint: 'watch strap' },
      { url: 'https://picsum.photos/seed/prod1-3/600/800', hint: 'watch side' },
    ],
    tags: ['Minimalist', 'Luxury', 'Leather'],
  },
  {
    id: '2',
    name: 'Nomad Urban Pack',
    description: 'Versatile backpack for the modern commuter.',
    longDescription: 'Crafted from water-resistant vegan leather, the Nomad Urban Pack is designed for life on the move. It includes a padded laptop compartment, multiple organizational pockets, and a sleek, low-profile design that complements any urban style.',
    price: 179.99,
    category: 'Accessories',
    rating: 4.9,
    reviews: 95,
    stock: 22,
    imageUrl: findImage('product-2').imageUrl,
    imageHint: findImage('product-2').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod2-1/600/800', hint: 'backpack front' },
      { url: 'https://picsum.photos/seed/prod2-2/600/800', hint: 'backpack interior' },
      { url: 'https://picsum.photos/seed/prod2-3/600/800', hint: 'backpack detail' },
    ],
    tags: ['Urban', 'Vegan', 'Commuter'],
  },
  {
    id: '3',
    name: 'Echo Wireless Cans',
    description: 'Immersive sound with noise-cancelling technology.',
    longDescription: 'Experience pure audio with the Echo Wireless Cans. Featuring advanced active noise-cancellation, plush memory foam earcups, and a 30-hour battery life, these headphones provide an unparalleled listening experience. Connect seamlessly via Bluetooth 5.2.',
    price: 349.0,
    category: 'Accessories',
    rating: 4.7,
    reviews: 250,
    stock: 8,
    imageUrl: findImage('product-3').imageUrl,
    imageHint: findImage('product-3').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod3-1/600/800', hint: 'headphones side' },
      { url: 'https://picsum.photos/seed/prod3-2/600/800', hint: 'headphones folded' },
      { url: 'https://picsum.photos/seed/prod3-3/600/800', hint: 'headphones on stand' },
    ],
    tags: ['Audio', 'Tech', 'Noise-Cancelling'],
  },
  {
    id: '4',
    name: 'Spectra Shades',
    description: 'Iconic sunglasses with polarized lenses.',
    longDescription: 'Protect your eyes in style with Spectra Shades. The polarized lenses reduce glare and provide 100% UV protection, while the lightweight, durable frame ensures all-day comfort. A timeless design for any face shape.',
    price: 129.5,
    category: 'Accessories',
    rating: 4.6,
    reviews: 78,
    stock: 30,
    imageUrl: findImage('product-4').imageUrl,
    imageHint: findImage('product-4').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod4-1/600/800', hint: 'sunglasses front' },
      { url: 'https://picsum.photos/seed/prod4-2/600/800', hint: 'sunglasses case' },
      { url: 'https://picsum.photos/seed/prod4-3/600/800', hint: 'sunglasses detail' },
    ],
    tags: ['Summer', 'UV Protection', 'Polarized'],
  },
  {
    id: '5',
    name: 'Strider Classic Kicks',
    description: 'Minimalist sneakers for everyday wear.',
    longDescription: 'The Strider Classic Kicks redefine casual footwear. Made with premium Italian leather and a cushioned sole, they offer superior comfort and a clean, versatile look that pairs with anything from jeans to chinos.',
    price: 199.99,
    category: 'Footwear',
    rating: 4.8,
    reviews: 154,
    stock: 12,
    imageUrl: findImage('product-5').imageUrl,
    imageHint: findImage('product-5').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod5-1/600/800', hint: 'sneakers side' },
      { url: 'https://picsum.photos/seed/prod5-2/600/800', hint: 'sneakers top' },
      { url: 'https://picsum.photos/seed/prod5-3/600/800', hint: 'sneakers pair' },
    ],
    tags: ['Casual', 'Leather', 'Everyday'],
  },
  {
    id: '6',
    name: 'Scribe Fountain Pen',
    description: 'A luxurious writing instrument.',
    longDescription: 'Rediscover the art of writing with the Scribe Fountain Pen. Its perfectly balanced body and smooth-flowing nib provide an exceptional writing experience. Each pen is a work of art, designed for those who appreciate the finer things.',
    price: 89.0,
    category: 'Accessories',
    rating: 4.9,
    reviews: 62,
    stock: 40,
    imageUrl: findImage('product-6').imageUrl,
    imageHint: findImage('product-6').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod6-1/600/800', hint: 'pen nib' },
      { url: 'https://picsum.photos/seed/prod6-2/600/800', hint: 'pen in box' },
      { url: 'https://picsum.photos/seed/prod6-3/600/800', hint: 'pen writing' },
    ],
    tags: ['Stationery', 'Luxury', 'Gift'],
  },
  {
    id: '7',
    name: 'Metropolitan Blazer',
    description: 'A sharp, modern-fit blazer.',
    longDescription: 'The Metropolitan Blazer is tailored for a modern silhouette from a premium wool blend. Its unstructured design allows for comfortable movement, making it the perfect piece to elevate a casual look or complete a formal ensemble.',
    price: 299.0,
    category: 'Apparel',
    rating: 4.7,
    reviews: 45,
    stock: 9,
    imageUrl: findImage('product-7').imageUrl,
    imageHint: findImage('product-7').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod7-1/600/800', hint: 'blazer fabric' },
      { url: 'https://picsum.photos/seed/prod7-2/600/800', hint: 'blazer lapel' },
      { url: 'https://picsum.photos/seed/prod7-3/600/800', hint: 'blazer on model' },
    ],
    tags: ['Formal', 'Wool', 'Modern'],
  },
  {
    id: '8',
    name: 'Terra Ceramic Mugs',
    description: 'Handcrafted mugs for your daily ritual.',
    longDescription: 'Start your day with the Terra Ceramic Mugs. Each mug is handcrafted by artisans, featuring a unique glaze and a comfortable, ergonomic handle. They are microwave and dishwasher safe, blending beauty with practicality.',
    price: 45.0,
    category: 'Accessories',
    rating: 5.0,
    reviews: 88,
    stock: 18,
    imageUrl: findImage('product-8').imageUrl,
    imageHint: findImage('product-8').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod8-1/600/800', hint: 'mug detail' },
      { url: 'https://picsum.photos/seed/prod8-2/600/800', hint: 'mug set' },
      { url: 'https://picsum.photos/seed/prod8-3/600/800', hint: 'mug in use' },
    ],
    tags: ['Handcrafted', 'Ceramic', 'Home'],
  },
  {
    id: '9',
    name: 'Zephyr Cashmere Scarf',
    description: 'An exceptionally soft and warm scarf.',
    longDescription: 'Wrap yourself in the unparalleled softness of the Zephyr Cashmere Scarf. Sourced from the finest Mongolian cashmere, it provides exceptional warmth without the weight. A versatile accessory for any winter wardrobe.',
    price: 150.0,
    category: 'Apparel',
    rating: 4.9,
    reviews: 55,
    stock: 14,
    imageUrl: findImage('product-9').imageUrl,
    imageHint: findImage('product-9').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod9-1/600/800', hint: 'scarf texture' },
      { url: 'https://picsum.photos/seed/prod9-2/600/800', hint: 'scarf worn' },
      { url: 'https://picsum.photos/seed/prod9-3/600/800', hint: 'scarf folded' },
    ],
    tags: ['Winter', 'Cashmere', 'Luxury'],
  },
  {
    id: '10',
    name: 'Orbit Smart Speaker',
    description: 'Voice-controlled smart home hub.',
    longDescription: 'The Orbit Smart Speaker delivers crisp vocals and rich bass, filling your room with 360-degree sound. With its built-in voice assistant, you can control your smart home, play music, and get answers to your questions, all hands-free.',
    price: 129.0,
    category: 'Accessories',
    rating: 4.6,
    reviews: 112,
    stock: 25,
    imageUrl: findImage('product-10').imageUrl,
    imageHint: findImage('product-10').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod10-1/600/800', hint: 'speaker top' },
      { url: 'https://picsum.photos/seed/prod10-2/600/800', hint: 'speaker in room' },
      { url: 'https://picsum.photos/seed/prod10-3/600/800', hint: 'speaker light' },
    ],
    tags: ['Smart Home', 'Tech', 'Audio'],
  },
  {
    id: '11',
    name: 'Vertex Leather Wallet',
    description: 'A slim, RFID-blocking wallet.',
    longDescription: 'The Vertex Wallet combines classic style with modern security. Made from full-grain leather, it develops a unique patina over time. The slim profile holds up to 10 cards and features RFID-blocking technology to protect your information.',
    price: 75.0,
    category: 'Accessories',
    rating: 4.8,
    reviews: 201,
    stock: 50,
    imageUrl: findImage('product-11').imageUrl,
    imageHint: findImage('product-11').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod11-1/600/800', hint: 'wallet open' },
      { url: 'https://picsum.photos/seed/prod11-2/600/800', hint: 'wallet with cards' },
      { url: 'https://picsum.photos/seed/prod11-3/600/800', hint: 'wallet leather' },
    ],
    tags: ['Leather', 'Security', 'Slim'],
  },
  {
    id: '12',
    name: 'Pulse ANC Earbuds',
    description: 'Compact earbuds with powerful sound.',
    longDescription: 'Enjoy your music anywhere with Pulse ANC Earbuds. They offer active noise cancellation in a compact, ergonomic design. Get up to 6 hours of playtime on a single charge, with an additional 24 hours from the wireless charging case.',
    price: 189.0,
    category: 'Accessories',
    rating: 4.7,
    reviews: 180,
    stock: 17,
    imageUrl: findImage('product-12').imageUrl,
    imageHint: findImage('product-12').imageHint,
    images: [
      { url: 'https://picsum.photos/seed/prod12-1/600/800', hint: 'earbuds in case' },
      { url: 'https://picsum.photos/seed/prod12-2/600/800', hint: 'earbud close' },
      { url: 'https://picsum.photos/seed/prod12-3/600/800', hint: 'earbuds charging' },
    ],
    tags: ['Audio', 'Tech', 'Wireless'],
  },
];
